[package]
name    = "summarise"
version = "0.1.0"
edition = "2021"

[lib]
name       = "summarise"
path       = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
serde      = { version = "1", features = ["derive"], default-features = false }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

#[profile.release]
#opt-level = "z"
#lto       = true
#strip     = true
