// crates/clawos-channels/src/lib.rs
//
// ClawOS channel abstraction layer.
//
// Defines the shared types and traits that all channels (Telegram, Web Gateway,
// LINE, etc.) must implement.  Previously each channel defined its own
// InboundMsg / GatewayEvent / GatewayState with no shared contract.
//
// Architecture:
//   ┌─────────────────────────────────────────────────────┐
//   │  Channel trait (this crate)                         │
//   │    ├── Telegram  (channels/telegram)                │
//   │    └── WebGateway (channels/web-gateway)            │
//   └─────────────────────────────────────────────────────┘
//              │ InboundMsg (user → agent)
//              ▼
//   ┌─────────────────────────┐
//   │  IPC / Agent Runtime    │
//   └─────────────────────────┘
//              │ OutboundEvent (agent → user)
//              ▼
//   Back to Channel

#![allow(dead_code)]
use anyhow::Result;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use tokio::sync::{broadcast, mpsc};
use uuid::Uuid;

// ── Shared message types ──────────────────────────────────────

/// A message arriving from a user via any channel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InboundMsg {
    /// Unique message ID (generated by the channel).
    pub id: String,
    /// Channel-scoped session identifier (Telegram chat_id, web session UUID, etc.).
    pub session_id: String,
    /// Raw text content of the message.
    pub content: String,
    /// Which channel this arrived from.
    pub source: ChannelKind,
    /// Wall-clock timestamp (Unix ms).
    pub timestamp: i64,
}

impl InboundMsg {
    pub fn new(
        session_id: impl Into<String>,
        content: impl Into<String>,
        source: ChannelKind,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            session_id: session_id.into(),
            content: content.into(),
            source,
            timestamp: chrono::Utc::now().timestamp_millis(),
        }
    }
}

/// An event streamed from the agent back to a user session.
#[derive(Debug, Clone)]
pub struct OutboundEvent {
    /// Must match the InboundMsg.session_id so the channel routes it correctly.
    pub session_id: String,
    /// Text fragment or complete response.
    pub content: String,
    /// True when this is the final event for this response.
    pub done: bool,
}

/// Which channel a message came from.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ChannelKind {
    Telegram,
    WebGateway,
    Shell,
    Unknown,
}

// ── Shared channel state ──────────────────────────────────────

/// The two ends of the channel ↔ agent message bus.
/// Passed to every channel at startup.
#[derive(Clone)]
pub struct ChannelBus {
    /// Channel → Agent: inbound user messages.
    pub inbound_tx: mpsc::Sender<InboundMsg>,
    /// Agent → Channel: outbound events broadcast to all subscribers.
    pub outbound_tx: broadcast::Sender<OutboundEvent>,
}

impl ChannelBus {
    /// Create a new bus.  `inbound_capacity` is the mpsc buffer size;
    /// `outbound_capacity` is the broadcast buffer (messages dropped when
    /// no receiver is keeping up — acceptable for streaming UIs).
    pub fn new(
        inbound_capacity: usize,
        outbound_capacity: usize,
    ) -> (Self, mpsc::Receiver<InboundMsg>) {
        let (inbound_tx, inbound_rx) = mpsc::channel(inbound_capacity);
        let (outbound_tx, _outbound_rx) = broadcast::channel(outbound_capacity);
        (
            Self {
                inbound_tx,
                outbound_tx,
            },
            inbound_rx,
        )
    }

    /// Subscribe to outbound events.
    pub fn subscribe_outbound(&self) -> broadcast::Receiver<OutboundEvent> {
        self.outbound_tx.subscribe()
    }

    /// Publish an outbound event to all channel subscribers.
    pub fn publish(&self, event: OutboundEvent) {
        // Ignore send errors — no active subscribers is fine (agent keeps running).
        let _ = self.outbound_tx.send(event);
    }
}

// ── Channel trait ─────────────────────────────────────────────

/// Every ClawOS channel (Telegram, Web Gateway, LINE, ...) implements this.
///
/// Lifecycle:
///   1. `Channel::new(config, bus)` — construct.
///   2. `channel.serve().await`     — run the event loop until shutdown.
#[async_trait]
pub trait Channel: Send + Sync {
    /// Human-readable channel name for logging (e.g. "telegram", "web-gateway").
    fn name(&self) -> &str;

    /// Run the channel's main loop.  Should not return until the channel shuts down.
    async fn serve(self: Box<Self>) -> Result<()>;

    /// Graceful shutdown signal.  Default: no-op (rely on task cancellation).
    async fn shutdown(&self) {}
}

// ── Session helpers ───────────────────────────────────────────

/// Serialisable session state stored in ClawFS.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SessionState {
    pub session_id: String,
    pub channel: String,
    /// Accumulated conversation turns (role + content pairs).
    pub turns: Vec<Turn>,
    /// Created at (Unix ms).
    pub created_at: i64,
    /// Last active at (Unix ms).
    pub updated_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Turn {
    pub role: String, // "user" | "assistant"
    pub content: String,
    pub ts: i64,
}

impl SessionState {
    pub fn new(session_id: impl Into<String>, channel: impl Into<String>) -> Self {
        let now = chrono::Utc::now().timestamp_millis();
        Self {
            session_id: session_id.into(),
            channel: channel.into(),
            turns: vec![],
            created_at: now,
            updated_at: now,
        }
    }

    pub fn add_turn(&mut self, role: impl Into<String>, content: impl Into<String>) {
        let ts = chrono::Utc::now().timestamp_millis();
        self.turns.push(Turn {
            role: role.into(),
            content: content.into(),
            ts,
        });
        self.updated_at = ts;
    }

    /// Keep only the most recent `max_turns` turns to bound memory.
    pub fn trim(&mut self, max_turns: usize) {
        if self.turns.len() > max_turns {
            let drain = self.turns.len() - max_turns;
            self.turns.drain(..drain);
        }
    }
}

// ── ClawFS session persistence helpers ───────────────────────

/// ClawFS path for a session's state blob.
pub fn session_path(channel: &str, session_id: &str) -> String {
    format!("/sessions/{channel}/{session_id}.json")
}

/// Serialise a SessionState to bytes for ClawFS storage.
pub fn encode_session(state: &SessionState) -> Result<Vec<u8>> {
    Ok(serde_json::to_vec(state)?)
}

/// Deserialise a SessionState from ClawFS bytes.
pub fn decode_session(bytes: &[u8]) -> Result<SessionState> {
    Ok(serde_json::from_slice(bytes)?)
}

// ── Tests ─────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inbound_msg_new_sets_fields() {
        let msg = InboundMsg::new("sess-1", "hello", ChannelKind::Telegram);
        assert_eq!(msg.session_id, "sess-1");
        assert_eq!(msg.content, "hello");
        assert_eq!(msg.source, ChannelKind::Telegram);
        assert!(!msg.id.is_empty());
    }

    #[test]
    fn session_state_add_and_trim() {
        let mut s = SessionState::new("s1", "telegram");
        s.add_turn("user", "hello");
        s.add_turn("assistant", "hi");
        s.add_turn("user", "bye");
        s.trim(2);
        assert_eq!(s.turns.len(), 2);
        assert_eq!(s.turns[0].role, "assistant");
    }

    #[test]
    fn session_encode_decode_roundtrip() {
        let mut state = SessionState::new("abc", "web-gateway");
        state.add_turn("user", "test message");
        let bytes = encode_session(&state).unwrap();
        let decoded = decode_session(&bytes).unwrap();
        assert_eq!(decoded.session_id, "abc");
        assert_eq!(decoded.turns.len(), 1);
    }

    #[tokio::test]
    async fn channel_bus_routes_outbound() {
        let (bus, _rx) = ChannelBus::new(16, 16);
        let mut sub = bus.subscribe_outbound();
        bus.publish(OutboundEvent {
            session_id: "s1".into(),
            content: "hello".into(),
            done: true,
        });
        let evt = sub.recv().await.unwrap();
        assert_eq!(evt.session_id, "s1");
        assert!(evt.done);
    }
}
